"""two phase stock transfer

Revision ID: 3ef04e588fec
Revises: ac5040244721
Create Date: 2026-07-29 00:46:16.751256

Hand-written rather than autogenerated: autogenerate on this database also
proposes ~40 tables of pre-existing drift (see ac5040244721 for the detail),
none of which belongs in a stock-transfer migration.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ef04e588fec'
down_revision: Union[str, Sequence[str], None] = 'ac5040244721'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('stock_transfers', sa.Column('dispatched_by', sa.String(length=64), nullable=True))
    op.add_column('stock_transfers', sa.Column('received_by', sa.String(length=64), nullable=True))
    op.add_column('stock_transfers', sa.Column('note', sa.String(length=256), nullable=True))
    # What actually arrived, kept apart from what was sent so a short delivery
    # stays visible instead of rewriting history.
    op.add_column(
        'stock_transfer_lines',
        sa.Column('qty_received', sa.Numeric(precision=10, scale=3), nullable=True),
    )


def downgrade() -> None:
    op.drop_column('stock_transfer_lines', 'qty_received')
    op.drop_column('stock_transfers', 'note')
    op.drop_column('stock_transfers', 'received_by')
    op.drop_column('stock_transfers', 'dispatched_by')
