"""menu_files

Revision ID: 464f76bc2e70
Revises: 683a8b807b47
Create Date: 2026-06-06 19:39:53.134131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '464f76bc2e70'
down_revision: Union[str, Sequence[str], None] = 'eb6f4dfb6f23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_files',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('restaurant_id', sa.BigInteger(), nullable=False),
    sa.Column('menu_id', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_files_menu_id'), 'menu_files', ['menu_id'], unique=False)
    op.create_index(op.f('ix_menu_files_restaurant_id'), 'menu_files', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_menu_files_sha256'), 'menu_files', ['sha256'], unique=False)
    op.execute(
        "CREATE TRIGGER trg_menu_files_updated_at BEFORE UPDATE ON menu_files "
        "FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS trg_menu_files_updated_at ON menu_files;")
    op.drop_index(op.f('ix_menu_files_sha256'), table_name='menu_files')
    op.drop_index(op.f('ix_menu_files_restaurant_id'), table_name='menu_files')
    op.drop_index(op.f('ix_menu_files_menu_id'), table_name='menu_files')
    op.drop_table('menu_files')
    # ### end Alembic commands ###
