"""composite_indexes_customers_orders

Revision ID: 4ed3145276fb
Revises: e99f4e761d39
Create Date: 2026-06-06 09:46:06.837244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ed3145276fb'
down_revision: Union[str, Sequence[str], None] = 'e99f4e761d39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate wanted to drop ix_dishes_name_normalized_trgm (raw-SQL GIN
    # index from e99f4e761d39, not in model metadata) — stripped, must stay.
    op.create_unique_constraint('uq_customers_restaurant_phone', 'customers', ['restaurant_id', 'phone'])
    op.create_index('ix_orders_restaurant_status', 'orders', ['restaurant_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orders_restaurant_status', table_name='orders')
    op.drop_constraint('uq_customers_restaurant_phone', 'customers', type_='unique')
    # ### end Alembic commands ###
