"""optout

Revision ID: 539d266a5dda
Revises: ce9e6a9b5dae
Create Date: 2026-06-06 15:15:56.191379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '539d266a5dda'
down_revision: Union[str, Sequence[str], None] = 'ce9e6a9b5dae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketing_opt_outs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('restaurant_id', sa.BigInteger(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id', 'phone')
    )
    op.create_index(op.f('ix_marketing_opt_outs_restaurant_id'), 'marketing_opt_outs', ['restaurant_id'], unique=False)
    # ### end Alembic commands ###

    # BEFORE UPDATE trigger for updated_at column
    op.execute(
        "CREATE TRIGGER trg_marketing_opt_outs_updated_at BEFORE UPDATE ON marketing_opt_outs "
        "FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS trg_marketing_opt_outs_updated_at ON marketing_opt_outs;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketing_opt_outs_restaurant_id'), table_name='marketing_opt_outs')
    op.drop_table('marketing_opt_outs')
    # ### end Alembic commands ###
