"""restaurants.is_active — deactivate a branch without deleting it

Closing a location must not delete the row. Its orders, staff, shifts and stock
counts all reference it, and last month's sales at that branch really happened;
dropping it would orphan those records and quietly rewrite the history the
rollups report on. So a closed branch is flagged, not removed.

Hand-written rather than autogenerated: this database has substantial pre-existing
model/schema drift, and `alembic revision --autogenerate` proposes dozens of
unrelated tables alongside the one column actually wanted.

Revision ID: 7c2d5b1e9f04
Revises: 6b1c4a90d2e7
"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

revision: str = "7c2d5b1e9f04"
down_revision: Union[str, Sequence[str], None] = "6b1c4a90d2e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default true so every existing branch stays open through the
    # deploy — a migration that closed live restaurants would stop service.
    op.add_column(
        "restaurants",
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
    )


def downgrade() -> None:
    op.drop_column("restaurants", "is_active")
