"""orders.guest_label — tell apart several bills sharing one table

Two parties can share a table and pay separately. The bills are ordinary orders
(``orders.table_id`` has no uniqueness constraint, so this was always legal at
the schema level), which means the cashier sees two rows differing only by id
and total. This column names them — "Guest 2", "Ahmed" — so the floor can label
which bill it is about to collect.

Nullable with no default ON PURPOSE: the overwhelming case is a table with one
bill, which needs no label at all, and back-filling every historical order with
"Guest 1" would invent a split that never happened.

Hand-written rather than autogenerated, for the reason given in 7c2d5b1e9f04:
this database has substantial pre-existing model/schema drift and autogenerate
proposes dozens of unrelated tables alongside the one column actually wanted.

Revision ID: 8d3e6c2b7a15
Revises: 7c2d5b1e9f04
"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

revision: str = "8d3e6c2b7a15"
down_revision: Union[str, Sequence[str], None] = "7c2d5b1e9f04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("orders", sa.Column("guest_label", sa.String(length=32), nullable=True))


def downgrade() -> None:
    op.drop_column("orders", "guest_label")
