"""dispatch_tables

Revision ID: 90f99618609c
Revises: bc71688df050
Create Date: 2026-06-06 15:05:09.728042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90f99618609c'
down_revision: Union[str, Sequence[str], None] = 'bc71688df050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('restaurant_id', sa.BigInteger(), nullable=False),
    sa.Column('rider_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('route', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_est_min', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batches_restaurant_id'), 'batches', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_batches_rider_id'), 'batches', ['rider_id'], unique=False)
    op.create_index(op.f('ix_batches_status'), 'batches', ['status'], unique=False)
    op.create_table('rider_locations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('rider_id', sa.BigInteger(), nullable=False),
    sa.Column('restaurant_id', sa.BigInteger(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rider_locations_restaurant_id'), 'rider_locations', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_rider_locations_rider_id'), 'rider_locations', ['rider_id'], unique=False)
    op.create_index(op.f('ix_rider_locations_ts'), 'rider_locations', ['ts'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('rider_id', sa.BigInteger(), nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('algorithm_score', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_order_id'), 'assignments', ['order_id'], unique=False)
    op.create_index(op.f('ix_assignments_rider_id'), 'assignments', ['rider_id'], unique=False)
    op.create_table('batch_orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_orders_batch_id'), 'batch_orders', ['batch_id'], unique=False)
    op.create_index(op.f('ix_batch_orders_order_id'), 'batch_orders', ['order_id'], unique=True)
    # ### end Alembic commands ###

    # BEFORE UPDATE triggers for updated_at columns (TimestampMixin convention).
    for t in ("batches", "batch_orders", "rider_locations", "assignments"):
        op.execute(
            f"CREATE TRIGGER trg_{t}_updated_at BEFORE UPDATE ON {t} "
            "FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
        )


def downgrade() -> None:
    """Downgrade schema."""
    for t in ("batches", "batch_orders", "rider_locations", "assignments"):
        op.execute(f"DROP TRIGGER IF EXISTS trg_{t}_updated_at ON {t};")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_batch_orders_order_id'), table_name='batch_orders')
    op.drop_index(op.f('ix_batch_orders_batch_id'), table_name='batch_orders')
    op.drop_table('batch_orders')
    op.drop_index(op.f('ix_assignments_rider_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_order_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_rider_locations_ts'), table_name='rider_locations')
    op.drop_index(op.f('ix_rider_locations_rider_id'), table_name='rider_locations')
    op.drop_index(op.f('ix_rider_locations_restaurant_id'), table_name='rider_locations')
    op.drop_table('rider_locations')
    op.drop_index(op.f('ix_batches_status'), table_name='batches')
    op.drop_index(op.f('ix_batches_rider_id'), table_name='batches')
    op.drop_index(op.f('ix_batches_restaurant_id'), table_name='batches')
    op.drop_table('batches')
    # ### end Alembic commands ###
