"""tables.merged_into_table_id — join several tables onto one invoice

A party of twelve sits across three tables and pays once. That is not the same
operation as the existing order merge, which cancels the second bill and frees
the second table immediately — correct when guests physically MOVE to one table,
wrong when they push tables together and are still sitting at both.

The secondary tables point at the table holding the bill. Both stay occupied
while the party eats, and settling the single invoice frees the whole group.

Self-referential FK on the same table, nullable: a table standing on its own —
the overwhelming majority — carries NULL.

Hand-written rather than autogenerated, for the reason given in 7c2d5b1e9f04:
this database has substantial pre-existing model/schema drift and autogenerate
proposes dozens of unrelated tables alongside the one column actually wanted.

Revision ID: 9f4a1d8e3b62
Revises: 8d3e6c2b7a15
"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

revision: str = "9f4a1d8e3b62"
down_revision: Union[str, Sequence[str], None] = "8d3e6c2b7a15"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "tables", sa.Column("merged_into_table_id", sa.BigInteger(), nullable=True)
    )
    op.create_index(
        "ix_tables_merged_into_table_id", "tables", ["merged_into_table_id"]
    )
    op.create_foreign_key(
        "fk_tables_merged_into_table_id",
        "tables",
        "tables",
        ["merged_into_table_id"],
        ["id"],
    )
    # Which of the primary's bills IS the group invoice. A table can carry several
    # at once, so a join is ambiguous without it — and food folded in would land on
    # a different bill from food ordered afterwards. No FK to orders.id: orders
    # already point at tables.id, and a second FK back makes the pair mutually
    # dependent, which alembic cannot order.
    op.add_column(
        "tables", sa.Column("group_bill_order_id", sa.BigInteger(), nullable=True)
    )
    op.create_index("ix_tables_group_bill_order_id", "tables", ["group_bill_order_id"])


def downgrade() -> None:
    op.drop_index("ix_tables_group_bill_order_id", table_name="tables")
    op.drop_column("tables", "group_bill_order_id")
    op.drop_constraint("fk_tables_merged_into_table_id", "tables", type_="foreignkey")
    op.drop_index("ix_tables_merged_into_table_id", table_name="tables")
    op.drop_column("tables", "merged_into_table_id")
