"""order_rider_fk_rider_performance

Revision ID: bc71688df050
Revises: 4ed3145276fb
Create Date: 2026-06-06 15:03:20.890058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc71688df050'
down_revision: Union[str, Sequence[str], None] = '4ed3145276fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('rider_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_orders_rider_id'), 'orders', ['rider_id'], unique=False)
    op.create_foreign_key('fk_orders_rider_id_riders', 'orders', 'riders', ['rider_id'], ['id'])
    # server_default backfills existing rider rows; matches the ORM default.
    op.add_column(
        'riders',
        sa.Column(
            'performance',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text(
                '\'{"on_time_pct": 100.0, "avg_delivery_min": 25, "total_deliveries": 0}\'::jsonb'
            ),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('riders', 'performance')
    op.drop_constraint('fk_orders_rider_id_riders', 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_rider_id'), table_name='orders')
    op.drop_column('orders', 'rider_id')
    # ### end Alembic commands ###
