"""sla_coupon_cod_tables

Revision ID: ce9e6a9b5dae
Revises: 90f99618609c
Create Date: 2026-06-06 15:07:53.587594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce9e6a9b5dae'
down_revision: Union[str, Sequence[str], None] = '90f99618609c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rider_shift_reconciliations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('rider_id', sa.BigInteger(), nullable=False),
    sa.Column('restaurant_id', sa.BigInteger(), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('expected_total_aed', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('collected_total_aed', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('variance_aed', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rider_shift_reconciliations_restaurant_id'), 'rider_shift_reconciliations', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_rider_shift_reconciliations_rider_id'), 'rider_shift_reconciliations', ['rider_id'], unique=False)
    op.create_index(op.f('ix_rider_shift_reconciliations_shift_date'), 'rider_shift_reconciliations', ['shift_date'], unique=False)
    op.create_table('cod_collections',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('rider_id', sa.BigInteger(), nullable=False),
    sa.Column('restaurant_id', sa.BigInteger(), nullable=False),
    sa.Column('amount_aed', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cod_collections_order_id'), 'cod_collections', ['order_id'], unique=True)
    op.create_index(op.f('ix_cod_collections_restaurant_id'), 'cod_collections', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_cod_collections_rider_id'), 'cod_collections', ['rider_id'], unique=False)
    op.create_table('coupons',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('restaurant_id', sa.BigInteger(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('discount_aed', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('redeemed_on_order_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['redeemed_on_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupons_code'), 'coupons', ['code'], unique=True)
    op.create_index(op.f('ix_coupons_customer_id'), 'coupons', ['customer_id'], unique=False)
    op.create_index(op.f('ix_coupons_order_id'), 'coupons', ['order_id'], unique=False)
    op.create_index(op.f('ix_coupons_restaurant_id'), 'coupons', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_coupons_status'), 'coupons', ['status'], unique=False)
    op.create_table('sla_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('restaurant_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notified', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sla_events_order_id'), 'sla_events', ['order_id'], unique=False)
    op.create_index(op.f('ix_sla_events_restaurant_id'), 'sla_events', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_sla_events_ts'), 'sla_events', ['ts'], unique=False)
    op.create_index(op.f('ix_sla_events_type'), 'sla_events', ['type'], unique=False)
    # ### end Alembic commands ###

    # BEFORE UPDATE triggers for updated_at columns (TimestampMixin convention).
    for t in ("sla_events", "coupons", "cod_collections", "rider_shift_reconciliations"):
        op.execute(
            f"CREATE TRIGGER trg_{t}_updated_at BEFORE UPDATE ON {t} "
            "FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
        )


def downgrade() -> None:
    """Downgrade schema."""
    for t in ("sla_events", "coupons", "cod_collections", "rider_shift_reconciliations"):
        op.execute(f"DROP TRIGGER IF EXISTS trg_{t}_updated_at ON {t};")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sla_events_type'), table_name='sla_events')
    op.drop_index(op.f('ix_sla_events_ts'), table_name='sla_events')
    op.drop_index(op.f('ix_sla_events_restaurant_id'), table_name='sla_events')
    op.drop_index(op.f('ix_sla_events_order_id'), table_name='sla_events')
    op.drop_table('sla_events')
    op.drop_index(op.f('ix_coupons_status'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_restaurant_id'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_order_id'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_customer_id'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_code'), table_name='coupons')
    op.drop_table('coupons')
    op.drop_index(op.f('ix_cod_collections_rider_id'), table_name='cod_collections')
    op.drop_index(op.f('ix_cod_collections_restaurant_id'), table_name='cod_collections')
    op.drop_index(op.f('ix_cod_collections_order_id'), table_name='cod_collections')
    op.drop_table('cod_collections')
    op.drop_index(op.f('ix_rider_shift_reconciliations_shift_date'), table_name='rider_shift_reconciliations')
    op.drop_index(op.f('ix_rider_shift_reconciliations_rider_id'), table_name='rider_shift_reconciliations')
    op.drop_index(op.f('ix_rider_shift_reconciliations_restaurant_id'), table_name='rider_shift_reconciliations')
    op.drop_table('rider_shift_reconciliations')
    # ### end Alembic commands ###
