"""marketing_tables

Revision ID: ea09f818d3c3
Revises: 539d266a5dda
Create Date: 2026-06-06 15:22:10.521261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea09f818d3c3'
down_revision: Union[str, Sequence[str], None] = '539d266a5dda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('segments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('restaurant_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('plain_english', sa.Text(), nullable=True),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_preview_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segments_restaurant_id'), 'segments', ['restaurant_id'], unique=False)
    op.create_table('wa_templates',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('restaurant_id', sa.BigInteger(), nullable=False),
    sa.Column('meta_template_name', sa.String(length=512), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('header', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('footer', sa.String(length=60), nullable=True),
    sa.Column('buttons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('ephemeral', sa.Boolean(), nullable=False),
    sa.Column('meta_template_id', sa.String(length=64), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id', 'meta_template_name', 'language', name='uq_wa_template_name_lang')
    )
    op.create_index(op.f('ix_wa_templates_restaurant_id'), 'wa_templates', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_wa_templates_status'), 'wa_templates', ['status'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('restaurant_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('template_id', sa.BigInteger(), nullable=True),
    sa.Column('segment_id', sa.BigInteger(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('coupon_value', sa.String(length=16), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['wa_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_restaurant_id'), 'campaigns', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_table('marketing_sends',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('restaurant_id', sa.BigInteger(), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('to_phone', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('wa_message_id', sa.String(length=128), nullable=True),
    sa.Column('error_code', sa.Integer(), nullable=True),
    sa.Column('converted_order_id', sa.BigInteger(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['converted_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'customer_id', name='uq_marketing_send_campaign_customer')
    )
    op.create_index(op.f('ix_marketing_sends_campaign_id'), 'marketing_sends', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_marketing_sends_customer_id'), 'marketing_sends', ['customer_id'], unique=False)
    op.create_index('ix_marketing_sends_phone_sent', 'marketing_sends', ['to_phone', 'sent_at'], unique=False)
    op.create_index(op.f('ix_marketing_sends_restaurant_id'), 'marketing_sends', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_marketing_sends_status'), 'marketing_sends', ['status'], unique=False)
    op.create_index(op.f('ix_marketing_sends_to_phone'), 'marketing_sends', ['to_phone'], unique=False)
    # ### end Alembic commands ###

    # BEFORE UPDATE triggers for updated_at column (one per new table)
    for table in ("segments", "wa_templates", "campaigns", "marketing_sends"):
        op.execute(
            f"CREATE TRIGGER trg_{table}_updated_at BEFORE UPDATE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
        )


def downgrade() -> None:
    """Downgrade schema."""
    for table in ("marketing_sends", "campaigns", "wa_templates", "segments"):
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_updated_at ON {table};")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketing_sends_to_phone'), table_name='marketing_sends')
    op.drop_index(op.f('ix_marketing_sends_status'), table_name='marketing_sends')
    op.drop_index(op.f('ix_marketing_sends_restaurant_id'), table_name='marketing_sends')
    op.drop_index('ix_marketing_sends_phone_sent', table_name='marketing_sends')
    op.drop_index(op.f('ix_marketing_sends_customer_id'), table_name='marketing_sends')
    op.drop_index(op.f('ix_marketing_sends_campaign_id'), table_name='marketing_sends')
    op.drop_table('marketing_sends')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_restaurant_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_wa_templates_status'), table_name='wa_templates')
    op.drop_index(op.f('ix_wa_templates_restaurant_id'), table_name='wa_templates')
    op.drop_table('wa_templates')
    op.drop_index(op.f('ix_segments_restaurant_id'), table_name='segments')
    op.drop_table('segments')
    # ### end Alembic commands ###
