"""sla_events_unique_order_type

Revision ID: eb6f4dfb6f23
Revises: f5b3d88a3a89
Create Date: 2026-06-06 18:45:09.664493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb6f4dfb6f23'
down_revision: Union[str, Sequence[str], None] = 'f5b3d88a3a89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_sla_events_order_type', 'sla_events', ['order_id', 'type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_sla_events_order_type', 'sla_events', type_='unique')
    # ### end Alembic commands ###
